### ISSUE TITLE
Feat: Add a Groq Chatbot in '/groq'

### ISSUE THREAD

**Issue by Subhadeep3902** [Subhadeep3902/pocketgpt#1]
- UI similar to the below

![image](https://github.com/Subhadeep3902/pocketgpt/assets/154616787/9f4970f3-3434-4e8c-96ea-de8c6c2f0106)

- Use markdown render nicely !! and `llama-70-b` model

**Comment by kom-senapati** [comment]
So is it the same as the Gemini bot, just with a different model

**Comment by kom-senapati** [comment]
I can add this
