### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by deepesh611** [Subhadeep3902/pocketgpt#10]
I have  a few suggestions for *README.md*.

1. You don't actually need a separate CONTRIBUTIONS.md. You can just add it in the README.md
2. You can set a bot i.e **@all-contributer** for adding the contributers.
3. In case you want to keep the contributing.md, it can be improved by adding the contributor's profile pics

**Comment by Subhadeep3902** [comment]
@deepesh611 go ahead !

**Comment by deepesh611** [comment]
thx, 

Work in Progress

**Comment by deepesh611** [comment]
I have uploaded a PR, pls review it and let me know your feedback, if it works or if you face any issues.

**Comment by kom-senapati** [comment]
You dont need to close prs just push commits to the branch and automatically they will appear to pr

**Comment by deepesh611** [comment]
Hi, I have submitted ac PR. Pls have a look and make sure to give a feedback

**Comment by deepesh611** [comment]
Hi there, pls make sure that you update my score on VSOC 🙏
